### ISSUE TITLE
Add a remote EJB example

### ISSUE THREAD

**Issue by manorrock** [manorrock/jakartaee-examples#10]

**Comment by manorrock** [comment]
@arjantijms Would this be an example that a web application calls a remote EJB, or a command-line calling a remote EJB? What is your preference here?

**Comment by arjantijms** [comment]
@manorrock I'd start with command-line calling a remote EJB ;)

**Comment by manorrock** [comment]
This is the tricky part of the JakartaEE environment. For the RI (Glassfish) it is possible to include a Maven dependency that is the app-client and then point it to the server and voila! Same hold for Payara as it is a Glassfish derivative, others not so much. WildFly does not even seem to support it.
