### ISSUE TITLE
Research CI/CD for OpenLiberty

### ISSUE THREAD

**Issue by manorrock** [manorrock/jakartaee-examples#47]
@rmpestano Can you have a look at this one?

**Comment by manorrock** [comment]
@rmpestano Can you have a look at this one?

**Comment by rmpestano** [comment]
Hi @manorrock, 

I think we first need to have a [chameleon container for liberty](https://github.com/arquillian/arquillian-container-chameleon/issues/28) , right?

**Comment by manorrock** [comment]
Yea I think so

**Comment by NottyCode** [comment]
Hi, So far I've got this far:

```
[INFO] JakartaEE Examples ................................. SUCCESS [  0.462 s]
[INFO] Utilities (for testing) ............................ SUCCESS [  4.284 s]
[INFO] Bean Validation Examples ........................... SUCCESS [  0.105 s]
[INFO] A BeanValidation @Min example ...................... SUCCESS [01:14 min]
[INFO] A BeanValidation @NotNull example .................. SUCCESS [01:09 min]
[INFO] A BeanValidation @Null example ..................... SUCCESS [01:01 min]
[INFO] A BeanValidation @Size example ..................... SUCCESS [01:00 min]
[INFO] EE Management Examples ............................. SUCCESS [  0.026 s]
[INFO] An EE Management Simple example .................... SUCCESS [  0.820 s]
[INFO] EE Security Examples ............................... SUCCESS [  0.125 s]
[INFO] An EE Security BASIC authentication example ........ SUCCESS [  2.555 s]
[INFO] An EE Security Custom Form with JSF example ........ SUCCESS [  1.725 s]
[INFO] An EE Security Filter example ...................... SUCCESS [  1.194 s]
[INFO] An EE Security FORM Authentication example ......... SUCCESS [  1.247 s]
[INFO] An EE Security In-memory IdentityStore example ..... SUCCESS [  1.222 s]
[INFO] An EE Security Servlet example ..................... SUCCESS [  0.944 s]
[INFO] EJB Examples ....................................... SUCCESS [  0.064 s]
[INFO] The remote EJB project ............................. SUCCESS [  0.028 s]
[INFO] The remote EJB JAR ................................. SUCCESS [  1.544 s]
[INFO] The remote EJB Client .............................. SUCCESS [  1.509 s]
[INFO] The remote EJB Enterprise application .............. SUCCESS [  1.426 s]
[INFO] A secured remote EJB example project ............... SUCCESS [  0.018 s]
[INFO] A secured remote EJB JAR ........................... SUCCESS [  0.422 s]
[INFO] A secured remote EJB Application Client ............ SUCCESS [  4.327 s]
[INFO] A secured remote EJB Enterprise application ........ SUCCESS [  0.746 s]
[INFO] JAX-RS Examples .................................... SUCCESS [  0.025 s]
[INFO] A JAX-RS @Consumes example ......................... SUCCESS [  0.892 s]
[INFO] A JAX-RS @DefaultValue example ..................... SUCCESS [01:04 min]
[INFO] A JAX-RS @DELETE example ........................... SUCCESS [  0.479 s]
```

**Comment by manorrock** [comment]
Is that running with an OpenLiberty profile, or just the default Maven invocation? See the azure-pipelines.yaml for an example, or let me know if you need more detailed information?

**Comment by NottyCode** [comment]
That was running with an OpenLiberty profile. However there are changes required in chameleon and in the Liberty managed container for arquillian and I haven't got a single run through yet.

**Comment by manorrock** [comment]
Great progress! Thank you for working on this!

**Comment by NottyCode** [comment]
So I've made good progress and managed to get everything to run. I need to do a lot of enablement (changes in multiple downstream dependencies), which I'll look into but it is promising.

**Comment by manorrock** [comment]
Great to hear! If needs be @rmpestano has worked on most of this stuff before, so if you have any questions ping him ;) Looking forward to adding OpenLiberty to the mix!

**Comment by NottyCode** [comment]
Right now I have it all working, but I need changes to be made to the Liberty Arquillian plugin, and then Chameleon needs an update.

**Comment by manorrock** [comment]
@rmpestano Can you help?

**Comment by rmpestano** [comment]
Hi, assuming we have a working remote and managed adapter for liberty and there is downloadable liberty server published to maven central in zip format (this is not required but simplifies things for chameleon) then it is a matter of creating an entry for liberty in [chameleon containers config file](https://github.com/arquillian/arquillian-container-chameleon/blob/master/arquillian-chameleon-container-model/src/main/resources/chameleon/default/containers.yaml).

**Comment by manorrock** [comment]
Do you need/want help from @rmpestano or me? If so can you open a PR with the changes? Or do you have it all tackled and we just need to wait for the dependencies to be updated?

**Comment by manorrock** [comment]
@NottyCode And how is it going?

**Comment by mnriem** [comment]
@NottyCode How is it going with the changes?

**Comment by mnriem** [comment]
Moved to eclipse-ee4j/jakartaee-examples
